/rogilink3:
  ros__parameters:
    motor0:
      encoder_cpr: 8192.0
      pos_limit:
        max: 2.7
        max_is_active_high: 1
        max_pin: 16
        min: 0.0
        min_is_active_high: 1
        min_pin: 0
      pos_pid:
        kd: 0.00
        ki: 0.02
        kp: 0.1
        vel_max: 0.05
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 1.0
    motor1:
      encoder_cpr: 8192.0
      pos_limit:
        max: 1.6
        max_is_active_high: 0
        max_pin: 0
        min: 0.0
        min_is_active_high: 1
        min_pin: 15
      pos_pid:
        kd: 0.05
        ki: 0.12
        kp: 1.3
      vel_max: 1.0
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 0.5
    motor2:
      encoder_cpr: 8192.0
      pos_limit:
        max: 10000.0
        max_is_active_high: 0
        max_pin: 0
        min: -10000.0
        min_is_active_high: 0
        min_pin: 0
      pos_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vel_max: 1.0
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 1.0
    motor3:
      encoder_cpr: 8192.0
      pos_limit:
        max: 10000.0
        max_is_active_high: 0
        max_pin: 0
        min: -10000.0
        min_is_active_high: 0
        min_pin: 0
      pos_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vel_max: 1.0
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 1.0
    motor4:
      encoder_cpr: 8192.0
      pos_limit:
        max: 10000.0
        max_is_active_high: 0
        max_pin: 0
        min: -10000.0
        min_is_active_high: 0
        min_pin: 0
      pos_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vel_max: 1.0
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 1.0
    motor5:
      encoder_cpr: 8192.0
      pos_limit:
        max: 10000.0
        max_is_active_high: 0
        max_pin: 0
        min: -10000.0
        min_is_active_high: 0
        min_pin: 0
      pos_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vel_max: 1.0
      vel_pid:
        kd: 0.0
        ki: 0.0
        kp: 0.0
      vol_max: 1.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

